### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by javl** [boehm-e/ofxARCore2#1]
I was wondering if you'd be willing to add the app you made with ofxARCore2 (the one you show in the animated gifs in the readme) as an example of how to use the addon.

I've been trying to make something similar (specifically with the floating images) but can't seem to find a way of storing a static texture, retrieved from the arcore camera texture (see here as well: https://forum.openframeworks.cc/t/no-method-copyto-in-oftexture-on-android/33136)

**Comment by boehm-e** [comment]
if you want to get  an image from the camera texture : 

```c
ofFbo * getImageFromArCore() {
    ofFbo *fbo = new ofFbo();
    fbo->allocate(ofGetWidth(), ofGetHeight());
    fbo->begin();
    ofSetColor(255, 255, 255);
    this->arcore->draw();
    fbo->end();
    return fbo;
}
```

Does it help ?

**Comment by javl** [comment]
Thank you, this was just what I needed. Such a stupidly simple solution...
The floating planes in my app seem a bit more jittery than in yours, but that might be some sort of optimalisation/rounding problem.

I also had to change `this->arcore->draw()` to `arcore.draw()` in my `ofApp.cpp` file for it to find the `arcore` object.

I might create a pull request later with my app and the ofxARCore(1) examples adapted to ofxARCore2, as it's always nice to have a starting point for these things.
